apiVersion: v1
kind: Service
metadata:
  name: tqt-redis-service
  labels:
    app:
      tqt-redis
spec:
  selector:
    app: tqt-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
