apiVersion: v1
kind: Service
metadata:
  name: tqt-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: tqt-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 6379
      nodePort: 30101
